[package]
name = "combined"
version = "0.1.0"
edition = '2018'
authors = ["johnginger <JohnGinger@users.noreply.github.com>"]

[dependencies]
regex = "1.1.0"
lazy_static = "1.2.0"
ascii = "0.9.1"
fnv = "1.0.6"
log ="0.4.6"
simplelog = "^0.2.0"